### ISSUE TITLE
Can't use MyEtherWallet to make ETC transactions

### ISSUE THREAD

**Issue by emartec** [estevaocm/bitkey#12]
Hi,

First of all, thank you for your investment to update that project that was seems to be left alone by the original developers. 

Just as for a background, I use the orignal BitKey and patching it with "a second USB key" that was containing additional "packages" (zip, tar, etc..) that I am unzipping in the BitKey "OS" in order to acheive the level of security I want for my transactions (offline, no network attached). Your contribution that could ultimately avoid that second key is god bless...

I will log few issue I have with my usage of Bitkey (and from your implementation from now on), if it can guide you on the evolution of the project. So, here is my first issue:

MyEtherWallet doesn't seems to be working with that version of Chronium when you want to make transactions on the ETC (Ethereum Classic) network. To reproduce:

- Start MyEtherWallet (MEW)
- On the dropdown (upper right) select "ETC (Epool.io)"
- Observe that after a reload, the page is still using the "standard" network

My initial patch was to unzip firefox on the system (with myetherwallet, not included in original BitKey) and load MEW in Firefox...

**Comment by estevaocm** [comment]
Hello, thanks for trying my fork and contributing to improve it.

So Firefox works as expected and Chromium not, correct? We can also try updating MEW, which has been updating fast.

I have not tested MEW with ETC, only ETH. Was actually surprised to get this request so soon. =)

**Comment by emartec** [comment]
I've tested it with a recent version, (downloaded about a week ago) and it doesn't work on the current version of Chronium included with bitkey. Maybe just updating the Chronium version, or install the latest version of firefox with bitkey....

**Comment by emartec** [comment]
Another question, not a issue.... How do you get Electrum for android to prepare unsigned transactions (based on specified public key) to be used by the QR scanner you included in Bitkey ?

**Comment by estevaocm** [comment]
Regarding Electrum for Android, prepare the transaction just as if it could be signed. Tap "Pay" and click the QR icon. Back at the Bitkey system, click Tools > Load transaction > From QR code. The webcam should function and display on the system. If it does not, you might have the same problem as #11 . In that case, we will have to investigate. Another option is to try running the QtQR, which is the red QR icon on Bitkey's desktop.

**Comment by estevaocm** [comment]
I have confirmed that Chromium in Bitkey is not working for ETC as you relate, even in the latest MEW version, and even though it does work in my Windows 10 Chrome.

**Comment by estevaocm** [comment]
It is strange that ETC works in Chromium in my Ubuntu 16 system, but not in Bitkey, whether offline or online. Will have to add Firefox then. Maybe even switch Chromium entirely.

**Comment by estevaocm** [comment]
Fixed. Release coming soon.
