### ISSUE TITLE
Bitkey "online" change system time

### ISSUE THREAD

**Issue by emartec** [estevaocm/bitkey#13]
When loading BitKey using the online mode, the system time (bios) is updated to the UTC timezone.
So, when I boot on windows after, my clock de-synchronized.

Try adding "UTC=no" to the "/etc/default/rcS" file:

https://askubuntu.com/questions/169376/clock-time-is-off-on-dual-boot

**Comment by estevaocm** [comment]
Fix commited.

**Comment by emartec** [comment]
For anyone having this issue, the recommended fix is to force your Windows system to consider the system clock as UTC.
https://wiki.archlinux.org/index.php/time

Quickly, create a ".reg" file with this content and merge it in the registry:


`
Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\TimeZoneInformation]
     "RealTimeIsUniversal"=dword:00000001
`
