### ISSUE TITLE
BIP 39 tool

### ISSUE THREAD

**Issue by LF76** [estevaocm/bitkey#14]
First of all, thanks for keeping up the project and adding LTC and BTC Cash. Those altcoins are more than welcome.

One little suggestion, as it's possible to generate the seed in Electrum by using BIP 39 (http://i.imgur.com/sVib4JS.jpg), could be useful (?) to include this or a similar tool in this regard, in BitKey?

https://github.com/iancoleman/bip39

**Comment by estevaocm** [comment]
Thanks for the suggestion, I've been looking for something like that just last night!

**Comment by LF76** [comment]
Glad to help, and thanks for looking into it. Also, Electrum has been updated today to v.3.0.3, if you could include it in your next release of Bitkey :)

**Comment by estevaocm** [comment]
Upgraded Electrum and added BIP39. Release coming soon.
