### ISSUE TITLE
Dash wallet for Electrum

### ISSUE THREAD

**Issue by LF76** [estevaocm/bitkey#25]
Just a suggestion, maybe it's another good tool for Bitkey:

https://electrum.dash.org
https://github.com/dashpay/electrum-dash

**Comment by estevaocm** [comment]
I have tested installing electrum-dash on Ubuntu before adding to Bitkey. It seems to have overwrited the normal Electrum, which is an undesirable behavior.

Other Electrum versions can have a packages directory with the necessary dependencies and run from source. This could probably avoid the problem above. However, Electrum-Dash does not provide this directory. I can test it with the packages directory for 2.X Electrum base but that may not be enough.

**Comment by estevaocm** [comment]
I was successful in running electrum-dash with Electrum 2.9.3 packages.

**Comment by estevaocm** [comment]
TODO: icon and wrapper

**Comment by estevaocm** [comment]
Related to #8

**Comment by estevaocm** [comment]
Icon and wrapper added.
