### ISSUE TITLE
Add Nano (RaiBlocks) wallet

### ISSUE THREAD

**Issue by firepol** [estevaocm/bitkey#28]
There is a RaiBlocks linux wallet, would be cool if you add it to bitkey: https://raiblocks.net/

**Comment by estevaocm** [comment]
I'll probably take a look but I'll have to investigate exactly how it works. Bitkey only persists data in a USB drive so I have to understand each wallet before simply adding it.

**Comment by firepol** [comment]
I just tested Nano (Raiblocks rebranded, now it's called Nano): https://nano.org/

The wallet is very simple to use: decompress it and run it... as sudo: `sudo ./nano_wallet`
... BUT...

it downloads the entire blockchain, so I was personally not patient enough for it. I guess we want to wait for a more "light" wallet, something that doesn't need to download the entire chain...

It's a very promising coin, 0 fees, advertized as "instant" (if you already downloaded the entire chain, else you need to download that first, so it's not instant at all ;) ), let's see how it goes. Maybe I'll comment here when there are developments from the nano team.

**Comment by estevaocm** [comment]
I've been keeping an eye on Raiblocks/Nano, but as you see, a light wallet such as Electrum would be best. IOTA also proposes 0 fees, though not instant, and I was seriously disappointed with their wallet. So adding a new wallet is pretty tricky.

**Comment by firepol** [comment]
Yeah, that's what I feel too, we need to wait for something similar to electrum... so for now I'd close this issuse and eventually comment back when nano offers a better wallet.

If IOTA releases a light wallet, that will be very welcome too, maybe we should "upvote" the feature if we find it, so hopefully devs will release something faster ;)

Thanks again.
