### ISSUE TITLE
Failed in build last version

### ISSUE THREAD

**Issue by aghamir** [estevaocm/bitkey#29]
![image](https://user-images.githubusercontent.com/1880925/36640948-4f592366-1a3d-11e8-8299-321940637aee.png)

**Comment by estevaocm** [comment]
For now, I suggest to try building from the last release tag.

**Comment by estevaocm** [comment]
I'll get that fixed when the next Electrum release, 3.1, comes out. I've been trying to reach the Electrum-Dash developer due to these compilation issues but I haven't got any response yet. I'll probably have to remove it from the build until it gets sorted out.

**Comment by emartec** [comment]
I just removed the `pyrcc4 ...` command from the `conf.d/04-wallet` file and it fixed the issue.
The fix is in my `Build fixed (electrum-dash icon) and Exodus Update` Pull request.

**Comment by estevaocm** [comment]
I'm sure it fixes compilation, but does ElectrumDash work?

**Comment by estevaocm** [comment]
Fixed with @emartec 's pull request
