### ISSUE TITLE
Cold-online

### ISSUE THREAD

**Issue by aghamir** [estevaocm/bitkey#30]
Can we have cold-online mode in this repo?

**Comment by estevaocm** [comment]
Not possible because there is no deseed function in Electrum anymore. What you can do is create a watch-only wallet in hot-online mode using the master public key of the cold-offline wallet.

**Comment by estevaocm** [comment]
However, for that kind of use, I recommend using the Electrum mobile app instead. Just import the master public key and only use the private key within Bitkey.

**Comment by aghamir** [comment]
Nice. Thanks

**Comment by estevaocm** [comment]
Happy to help.
